---
  title: "Curves of Lineage Specific Gene Cluster Expression"
author: "Russell Fletcher"
date: '`r Sys.Date()`'
output:
  html_document:
  code_folding: hide
toc: yes
toc_float: yes
fig_width: 10
fig_height: 10
---
  
```{r options, echo=FALSE, results="hide",mesasge=FALSE, error=FALSE,include=FALSE}
knitr::opts_chunk$set(fig.align="center", cache=TRUE, error=FALSE, message=FALSE, warning=FALSE, results="hide")

library(clusterExperiment)
library(RColorBrewer)

expt_str <- "oeHBCdiff"
out_dir <- file.path("../output/clust", expt_str)
DE_dir = file.path("../output/DE", expt_str)
DEG_dir <- file.path("../output/DEG", expt_str)
viz_dir <- file.path("../output/viz", expt_str)

load(file.path(out_dir, paste0(expt_str,"_lineagedata.Rda")))
load(file.path(DE_dir,"NL_SL_oneVall500DE_genes.Rda"))

gcolpal <- c(brewer.pal(8,"Dark2")[-c(2,3,5)],brewer.pal(12,"Paired")[c(1,2,8,10,9)],brewer.pal(12,"Set3")[c(7,8,12)], brewer.pal(8, "Pastel2")[8], brewer.pal(11,"BrBG")[11], brewer.pal(11,"PiYG")[1], "cyan", "darkblue","darkorchid2", "brown1", "springgreen1", "deepskyblue4", "darkolivegreen","antiquewhite2")

colpal <- c("#1B9E77","antiquewhite2","cyan","#E7298A","#A6CEE3","#666666","#E6AB02","#FFED6F","darkorchid2","#B3DE69","#FF7F00","#A6761D","#1F78B4")   

ccn <- colpal[-c(4,6,10,13)]
ccs <- colpal[-c(2,3,8:13)]

```


```{r geneClusterCurvePrep}

NLgClBList <- c("m1","m2","m3","m4","m5","m6","m7","m8","m9","m10","m11","m12","m13","m14","m15","m16","m17")
SLgClBList <- c("m1","m2","m3","m4","m5","m6","m7","m8","m9","m10","m11","m12")

NLgClMatList <- lapply(NLgClBList, function(x){
  NLgclm <- nlm[colnames(cegNL)[primaryClusterNamed(cegNL)==x],]
  return(NLgclm)})

SLgClMatList <- lapply(SLgClBList, function(x){
  SLgclm <- slm[colnames(cegSL)[primaryClusterNamed(cegSL)==x],]
  return(SLgclm)
})


```

```{r geneClusterCurves}

#####-----To plot each gene cluster individually with Lowess
geneClCurves <- function(gClmatList, devO, linMat, clusters, colorV, geneColorV, lineage) {
  geneClPlotCurves <- lapply(seq_along(gClmatList), function(x){
    pdf(file=file.path(viz_dir,paste0(lineage,"_GeneClCurve_",x,".pdf")),height=7, width=8)
    tmp <- t(scale(t(gClmatList[[x]])))
    cellMean <- apply(tmp, 2, mean) 
    cellSD <- apply(tmp, 2, sd)
    cellSEM <- cellSD/sqrt(nrow(tmp))
    devO <- order(devO); names(devO) <- colnames(linMat)
    names(cellMean) <- names(devO); names(cellSD) <- names(devO); names(cellSEM) <- names(devO)
    SEMm <- cellMean-cellSEM; SEMp <- cellMean + cellSEM
    plot(devO, cellMean, col=colorV[clusters],xlab=paste0(lineage," Lineage Developmental Order"),ylab="Average z score",  pch=19, ylim=c(-1.5,3), lwd=0.1, cex=1);
    arrows(devO, SEMm, devO, SEMp,length=0.05,angle=90,code=3,lwd=0.05, col=colorV[clusters])
    lines(lowess(devO,cellMean,f=0.12, delta=2), lwd=1,col=geneColorV[x])
    dev.off()
  })
}

geneClCurves(NLgClMatList, NLdevO, nlm, nlclusters, ccn, gcolpal, lineage="Neuronal")
geneClCurves(SLgClMatList, SLdevO, slm, slclusters, ccs, gcolpal, lineage="Sustentacular")

#####-----To plot all gene cluster curves together, fit only, no error bars
geneClCurvesAllInOne <- function(gClmatList, devO, geneColorV, lineage) {
gClScaledMats <- lapply(gClMatList, function(x){
  tmp <- t(scale(t(x)))
  cellMean <- apply(tmp,2,mean)
  names(cellMean) <- names(devO)
  DOmat <- matrix(devO)
  DOmat <- cbind(devO, cellMean)
  return(DOmat)})

pdf(file=file.path(viz_dir,paste0(lineage, "_AllGeneClCurves.pdf"), height=7,length=8))
plot(gClScaledMats[[1]], col=NULL, xlab=paste0(lineage, " Lineage Developmental Order"),ylab="Average z score", main=paste(lineage, "Lineage Gene Cluster Expression",sep=" "), pch=19,ylim=c(-1.5,2.25))
lapply(seq_along(gClScaledMats),function(x){
  lines(lowess(gClScaledMats[[x]], f=0.12, delta=2),lwd=0.5,col=geneColorV[x])
})
} 

geneClCurvesAllInOne(NLgClMatList, NLdevO, gcolpal, lineage= "Neuronal")
geneClCurvesAllInOne(SLgClMatList, SLdevO, gcolpal, lineage= "Sustentacular")

```

