---
title: "Lineage Specific Gene Clustering"
author: "Russell Fletcher"
date: '`r Sys.Date()`'
output:
html_document:
code_folding: hide
toc: yes
toc_float: yes
fig_width: 10
fig_height: 10
---

```{r options, echo=FALSE, results="hide",mesasge=FALSE, error=FALSE,include=FALSE}
knitr::opts_chunk$set(fig.align="center", cache=TRUE, error=FALSE, message=FALSE, warning=FALSE, results="hide")

library(clusterExperiment)
library(RColorBrewer)

expt_str <- "oeHBCdiff"
clust_dir <- file.path("../output/clust", expt_str)
DE_dir <- file.path("../output/DE", expt_str)
gClust_dir <- file.path("../output/gClust", expt_str)

load(file.path(clust_dir, paste0(expt_str,"_lineageData.Rda")))
load(file.path(DE_dir,"NL_SL_oneVall500DE_genes.Rda"))

```

### Preparation for gene clustering
```{r geneClusteringPreparation}

NL_DEgmat <- t(nlm[NL_DEgenes, ])
SL_DEgmat <- t(slm[SL_DEgenes, ])

```

### Gene Clustering: clusterMany using PAM
```{r geneClustering}

minSize <- 1
seed <- 927501

NL_DEgm <- scale(NL_DEgmat)
nlGeneCl<- clusterMany(NL_DEgm, dimReduce="none", clusterFunction=c("pam"),
                minSizes=minSize, subsample=F, sequential=F, ncores=detectCores(),
                random.seed=seed, run=TRUE, ks = 4:15, verbose=TRUE, isCount=FALSE)

save(nlGeneCl,beta,minSize, seed, file=file.path(clust_dir, paste0(expt_str,"_NLgeneCl.Rda")))

SL_DEgm <- scale(SL_DEgmat)
slGeneCl<- clusterMany(SL_DEgm, dimReduce="none", clusterFunction=c("pam"),
                minSizes=minSize, subsample=F, sequential=F, ncores=detectCores(),
                random.seed=seed, run=TRUE, ks = 4:15, verbose=TRUE, isCount=FALSE)
save(slGeneCl,minSize, seed, file=file.path(clust_dir, paste0(expt_str,"_SLgeneCl.Rda")))
```


```{r MergingGeneClusters}

breakv <- c(min(nlm), seq(0, quantile(nlm[nlm > 0], .99, na.rm = TRUE), length = 50), max(nlm))

geneClConsensusMerge <- function(geneClusters, cutoff, lineageName) {
  ceg <- combineMany(geneClusters, proportion=0.7, minSize=10,propUnassigned=0.9, clusterFunction="hierarchical01")
  plotClusters(ceg)
  plotCoClustering(ceg)
  ceg <- makeDendrogram(ceg,dimReduce="none", ignoreUnassignedVar=TRUE)
  ceg <- mergeClusters(ceg, mergeMethod="locfdr", plotType="mergeMethod", cutoff=cutoff)
  assign(paste0("ceg", lineageName), ceg)
  save(list=paste0("ceg", lineageName), file=file.path(gClust_dir,paste0(expt_str, "_", lineageName, "_geneCl_final.Rda")))
  return(ceg)
}

cegNL <- geneClConsensusMerge(nlGeneCl, 0.04, "NL")

cegSL <- geneClConsensusMerge(slGeneCl, 0.02, "SL")

```
