---
  title: "oeHBCdiff DE"
author: "Russell Fletcher"
date: '`r Sys.Date()`'
output:
  html_document:
  code_folding: hide
toc: yes
toc_float: yes
fig_width: 10
fig_height: 10
---
  
```{r options, echo=TRUE, results="markup",message=FALSE, error=FALSE}
knitr::opts_chunk$set(cache=FALSE, fig.align="center", fig.width=10, error=TRUE,message=TRUE, echo=TRUE, warning=TRUE,results="markup")
library(clusterExperiment)
library(limma)
```

###Set-up and loading data
``` {r loading&set-up}

expt_str <- "oeHBCdiff"

clust_dir <- file.path("../output/clust", expt_str)
DE_dir <- file.path("../output/DE", expt_str)

load(file.path(clust_dir, paste0(expt_str,"_lineageData.Rda")))

```

### Lineage specific differential expression analysis:
## Neuronal and Sustentacular cell lineage limma DE analysis
``` {r differentialExpression}

NLoneVallDE500 <- getBestFeatures(nlm, nclus.labels, contrastType="OneAgainstAll",number=500, p.value=0.05)
write.table(NLoneVallDE500, file.path(DE_dir,"NL_DE_oneVall_limma_500.txt"),quote=FALSE,sep="\t")
NLpairsDE500 <- getBestFeatures(nlm, nclus.labels, contrastType="Pairs",number=500, p.value=0.05)
write.table(NLpairsDE500, file.path(DE_dir,"NL_DE_Pairs_limma_500.txt"),quote=FALSE,sep="\t")

SLoneVallDE500 <- getBestFeatures(slm, sclus.labels, contrastType="OneAgainstAll",number=500, p.value=0.05)
write.table(SLoneVallDE500, file.path(DE_dir,"SL_DE_oneVall_limma_500.txt"),quote=FALSE,sep="\t")
SLpairsDE500 <- getBestFeatures(slm, sclus.labels, contrastType="Pairs",number=500, p.value=0.05)
write.table(SLpairsDE500, file.path(DE_dir,"SL_DE_Pairs_limma_500.txt"),quote=FALSE,sep="\t")

NL_DEgenes <- unique(NLoneVallDE500$Feature)
SL_DEgenes <- unique(SLoneVallDE500$Feature)

save(NL_DEgenes, SL_DEgenes, file=file.path(DE_dir,"NL_SL_oneVall500DE_genes.Rda"))

```

